syntax = "proto3";

package sops.v1;

import "google/protobuf/struct.proto";

service KmsService {
  rpc Encrypt(EncryptRequest) returns (EncryptResponse);
  rpc Decrypt(DecryptRequest) returns (DecryptResponse);
}

message EncryptRequest {
  optional bytes plaintext = 1;
  google.protobuf.Struct configuration = 2;
}

message EncryptResponse {
  optional bytes ciphertext = 1;
}

message DecryptRequest {
  optional bytes ciphertext = 1;
  google.protobuf.Struct configuration = 2;
}

message DecryptResponse {
  optional bytes plaintext = 1;
}
